"""new fields in user model

Revision ID: 34b366bfe41f
Revises: 10d48a65b16f
Create Date: 2020-06-19 00:19:10.474283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b366bfe41f'
down_revision = '10d48a65b16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement', 'name')
    # ### end Alembic commands ###
